---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: copy NetworkManager config
  copy:
    src: NetworkManager.conf
    dest: /etc/NetworkManager/NetworkManager.conf
  notify: restart NetworkManager

- name: ensure resolv.conf present from template
  template:
    src: resolv.conf.j2
    dest: "/etc/resolv.conf"
    group: root
    owner: root
    mode: "0644"
  notify: restart NetworkManager
