---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: ensure core packages installed
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
